collections:
  comics:
    output: true
    permalink: /comic/:name/

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: comics
    values:
      layout: comic
  - scope:
      path: ""
      type: posts
    values:
      layout: post

paginate: 10
paginate_path: "/page:num/"

