collections:
  comics:
    output: true
    permalink: /comic/:basename/

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: comics
    values:
      layout: comic
  - scope:
      path: ""
      type: posts
    values:
      layout: post

